version: "3"
services:
  node:
    container_name: ypp-sim-server
    restart: always
    build: .
    image: artishy/ypp-sim-server:latest
    env_file:
      - docker-compose.env
    ports:
      - "4000:4000"
    links:
      - mongo
      - redis
  mongo:
    container_name: ypp-sim-db
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  redis:
    container_name: ypp-sim-cache
    restart: always
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
